version: '3.8'

services:
  central_server:
    container_name: central_server
    build: ./central_server
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./central_server:/code
      - node_modules:/code/node_modules

  mqtt_broker:
    container_name: mqtt_broker
    image: emqx/emqx
    ports:
      - 1883:1883
      - 8081:8081
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    environment:
      - EMQX_NAME=mqtt_broker
      - EMQX_HOST=localhost
volumes:
  node_modules:
